### ISSUE TITLE
Possible issues and notes regarding UE5

### ISSUE THREAD

**Issue by TheAshenWolf** [TheAshenWolf/WakaTimeForUE#23]
Today, I have renamed the plugin from WakaTimeForUE4 to just WakaTimeForUE; the reason for this was the fact, that UE5 is out and the plugin is (more or less) compatible with UE5.

This issue will be kept open while it is true, so check it in case there is an issue. It might be listed here.

**Possible issues**
- There is an issue stating something about having the plugin in UE5Modules and whatnot... the solution to this issue is to move the plugin from the engine to the project.

**Comment by danglingptr0x0** [comment]
#24

**Comment by gtnardy** [comment]
looking forward to the official next update (also to fix the warnings 😜)

**Comment by Laaouatni** [comment]
in a standard folder structure of a UE5 project like this:

```
.
└── MyProject
    ├── Config
    │   ├── DefaultEditor.ini
    │   ├── DefaultEditorPerProjectUserSettings.ini
    │   ├── DefaultEngine.ini
    │   ├── DefaultGame.ini
    │   └── DefaultInput.ini
    ├── Content
    │   ├── Blueprints
    │   ├── Characters
    │   ├── Collections
    │   ├── Developers
    │   ├── __ExternalActors__
    │   ├── __ExternalObjects__
    │   ├── LevelPrototyping
    │   ├── StarterContent
    │   └── ThirdPerson
    ├── DerivedDataCache
    │   └── VT
    ├── Intermediate
    │   ├── CachedAssetRegistry_0.bin
    │   ├── Config
    │   ├── ReimportCache
    │   └── ShaderAutogen
    ├── MyProject.uproject
    └── Saved
        ├── Autosaves
        ├── AutoScreenshot.png
        ├── Collections
        ├── Config
        ├── Crashes
        ├── Logs
        └── SourceControl
```

> Where I need to paste the `WakaTimeForUE` folder? 
> I dont see any Plugin folder, so I don't get where I need to insert the folder.

**Comment by danglingptr0x0** [comment]
> in a standard folder structure of a UE5 project like this:
> 
> ```
> .
> └── MyProject
>     ├── Config
>     │   ├── DefaultEditor.ini
>     │   ├── DefaultEditorPerProjectUserSettings.ini
>     │   ├── DefaultEngine.ini
>     │   ├── DefaultGame.ini
>     │   └── DefaultInput.ini
>     ├── Content
>     │   ├── Blueprints
>     │   ├── Characters
>     │   ├── Collections
>     │   ├── Developers
>     │   ├── __ExternalActors__
>     │   ├── __ExternalObjects__
>     │   ├── LevelPrototyping
>     │   ├── StarterContent
>     │   └── ThirdPerson
>     ├── DerivedDataCache
>     │   └── VT
>     ├── Intermediate
>     │   ├── CachedAssetRegistry_0.bin
>     │   ├── Config
>     │   ├── ReimportCache
>     │   └── ShaderAutogen
>     ├── MyProject.uproject
>     └── Saved
>         ├── Autosaves
>         ├── AutoScreenshot.png
>         ├── Collections
>         ├── Config
>         ├── Crashes
>         ├── Logs
>         └── SourceControl
> ```
> 
> > Where I need to paste the `WakaTimeForUE` folder?
> > I dont see any Plugin folder, so I don't get where I need to insert the folder.

@Laaouatni 
If it doesn't exist, create it in the project root (`projectName/Plugins`)

refs:
https://docs.unrealengine.com/5.0/en-US/plugins-in-unreal-engine/
https://forums.unrealengine.com/t/which-folder-should-i-place-the-plug-in-i-created-in-order-to-add-it-to-my-game-project/678962

**Comment by VerzatileDev** [comment]
Heya I have rebuilt the plugin and fixed the errors that it seems to hand out when trying to use it on UE5.

- I seem to be getting Correct Heartbeats (at least according to the log system you have setup) 
- Tried Both (Engine Folder Plugins ), ( Project Plugins )  " Both seem to be sending heartbeats.

Though I think it fails to submit the statistic to the website itself, I may be wrong but similarly I saw the same issue for the UE4 version which was listed in the releases.


Any suggestions?

**Comment by TheAshenWolf** [comment]
Hey! Have you tried this?
> 4.1. In recent changes, API key on the website appears in format `waka_[apiKey]`, in order for this to work, remove the `waka_` prefix.

**Comment by VerzatileDev** [comment]
> Hey! Have you tried this?
> 
> > 4.1. In recent changes, API key on the website appears in format `waka_[apiKey]`, in order for this to work, remove the `waka_` prefix.

-  ~The website database expects to recive it with a prefix "waka_~ ", ~which can no longer be changed on the website.~ 

- ~I have tried it without a prefix and with the prefix.~ ( See The New comment )

- As far I'm aware it was changed due to the partnership of github which added the prefix " waka_ " as for reference https://github.blog/changelog/2023-02-10-wakatime-is-now-a-github-secret-scanning-partner/ 


There are currently only two people who have succesfully managed to get it working at least according to the leaderboards

https://wakatime.com/leaders/language/unreal%20engine



See an Update to this " https://github.com/TheAshenWolf/WakaTimeForUE/issues/23#issuecomment-2152268249 "

**Comment by VerzatileDev** [comment]
I have seemed to figured out the reason of sending successful heartbeats, but not showing up as data on the wakatime website.

Seems the issue is in relation to the CLI system used it must be compatible with the PreFix used, Where the lates currently available one 1.90 uses with a prefix, whereas your current setup is done with an older version of a prefix which should be updated.


![image](https://github.com/TheAshenWolf/WakaTimeForUE/assets/47317248/bd4e6fa3-665a-4a5a-9b5c-e2c808ad4727)


As it seems the lates used is [1.90.0](https://github.com/wakatime/wakatime-cli/releases) 

That seems to be the issue as far As I can see at the current moment.

As for more reference when I force with the Prefix " waka_ " to any other IDe language or what not I would recive the following 

`" {"caller":"/Users/runner/work/wakatime-cli/wakatime-cli/cmd/legacy/run.go:189","func":"runCmd","level":"error","message":"failed to run command: failed to send heartbeat: invalid api key format. Find your api key from wakatime.com/settings/api-key","now":"2024-06-05T22:59:28+03:00","version":"v1.18.9"} " As that version requires that the prefix is not used.  `


By that I assume it would only fix the issue 

- if or when the CLI is changed each time it sends the Unreal information (With the current code)
- Which also Requires the removal of the prefix " waka_ " when it is being sent.

Or simply would be to change the CLI to the plugin itself and update it on the website.

**Comment by TheAshenWolf** [comment]
Thanks a lot for the info; I never realized the CLI version is hardcoded in there. Created issue #36 for this; will try to update as soon as possible.

**Comment by VerzatileDev** [comment]
Important note with 1.2.5 and later versions:

When you wish to build the Plugin itself, you cannot do it through `Engine-> plugins`

- For that, you are required to add the Plugin to one of your projects `Project -> plugins(folder) -> Plugin`, which rebuilds the ( Binaries and Interimiadte folders).

After it is built it can be added to `Engine -> plugins` for it to work properly.

**Comment by EddieDover** [comment]
I had a bit of trouble getting this to work today, thankfully @VerzatileDev solved the first part of my problem, but apparently this plugin also looks for an `api_url` which is an **optional** field in the config. I was missing that.

If you don't have it, and want it to default to wakatime's own server, the value that you will need to add will be `https://api.wakatime.com/api/v1`
